[SOL] Add missing space in error message about stack usage (#149)
The compiler sometimes reports:

    Error: A function call in method [...] overwrites values in the
    frame. Please, decrease stack usage or remove parameters from the
    call.The function call may cause undefined behavior during execution.

Add a missing space between "call." and "The function".

Fixes: https://github.com/anza-xyz/llvm-project/issues/146